services:
  app:
    # Menggunakan Dockerfile.dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nextjs_app
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT_INTERNAL}/${DB_NAME}?schema=public"
      CHOKIDAR_USEPOLLING: "true"
    # Kita HAPUS 'command: npm run dev' karena sudah ada di CMD Dockerfile.dev

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    ports:
      - "${DB_PORT_EXTERNAL}:${DB_PORT_INTERNAL}"
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: